---
title: "workout02-nadia-aquil.Rmd"
author: "Nadia Aquil"
date: "4/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(shiny)
library(ggplot2)
library(rsconnect)
```

```{r, eval = TRUE, echo=FALSE}

#' @title future_value
#' @description finds future value of savings
#' @param amount, rate, years: starting amount, return rate in percent, and time in years
#' @return computed future value
future_value <- function(amount, rate, years){
  return(amount*((1+rate)^years))
}

#' @title annuity
#' @description finds future value of annuity
#' @param contrib, rate, years: initial contribution, return rate in percent, and time in years
#' @return computed savings value
annuity <- function(contrib, rate, years){
  return(contrib*(((1+rate)^years - 1)/rate))
}

#' @title annuity
#' @description finds future value of growing annuity
#' @param contrib, rate, growth, years: initial contribution, return rate in percent, growth rate in percent, and time in years
#' @return computed savings value
growing_annuity <- function(contrib, rate, growth, years){
  n <- (1+rate)^years - (1+growth)^years
  return(contrib * (n/(rate - growth)))
}
```

```{r, eval= TRUE, echo=FALSE}
ui <- fluidPage(
  titlePanel("Savings Simulation"),
  
     # Sidebar with a slider input for number of bins 
   sidebarLayout(
      fluidRow(
         column(4, wellPanel(sliderInput("initial",
                     "Initial amount",
                     min = 0,
                     max = 100000,
                     value = 1000,
                     step = 500))),
         column(4, wellPanel(sliderInput("rate", "Return rate (in %)",
                     min = 0, max = 20,
                     value = 5, step = .1))),
         column(4, wellPanel(sliderInput("annual", "Annual Contribution",
                     min = 0, max = 50000,
                     value = 2000,
                     step = 500))),
          column(4, wellPanel(sliderInput("growth_rate", "Growth Rate (in %)",
                     min = 0, max = 20,
                     value = 2, step = .1))),
         column(4, wellPanel(sliderInput("years", "Years",
                     min = 0, max = 50,
                     value = 20))),
          column(4, wellPanel(selectInput("facet", "Facet?",
                      choices = c("no", "yes")))
          )
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
         plotOutput("distPlot"),
         
      
    
     tableOutput("table")
       
      )
   )
  
)
# Define server logic required to draw a histogram
server <- function(input, output) {
  
  dat <- reactive({
    year <- 0
    amt <- input$initial
    no_contrib <- rep(amt, input$years)
    fixed_contrib <- rep(amt, input$years)
    growing_contrib <- rep(amt, input$years)
 
    rate <- input$rate * .01
    growth <- input$growth_rate * .01
    contrib <- input$annual
    for (i in 0:input$years - 1){
      no_contrib[i+ 1] <- future_value(amt, rate, year)
      fixed_contrib[i + 1] <- future_value(amt, rate, year)  + annuity(contrib, rate, year)
      growing_contrib[i + 1] <- future_value(amt, rate, year)  + growing_annuity(contrib, rate, growth, year)
      year <- year + 1
    }

    year <- seq(1, input$years)
    modalities <- rbind(year, no_contrib)
    modalities <- rbind(modalities, fixed_contrib)
    modalities <- rbind(modalities, growing_contrib)
    modalities <- t(modalities)
    modalities <- data.frame(modalities)
    modalities <- reshape2::melt(modalities, id.var = 'year')
    dat <- modalities
    return(dat)
  })
  
  tab <- reactive({
    year <- 0
    amt <- input$initial
    no_contrib <- rep(0, input$years)
    fixed_contrib <- rep(0, input$years)
    growing_contrib <- rep(0, input$years)
 
    rate <- input$rate * .01
    growth <- input$growth_rate * .01
    contrib <- input$annual
    for (i in 0:input$years -1){
      no_contrib[i + 1] <- future_value(amt, rate, year)
      fixed_contrib[i + 1] <- future_value(amt, rate, year)  + annuity(contrib, rate, year)
      growing_contrib[i + 1] <- future_value(amt, rate, year)  + growing_annuity(contrib, rate, growth, year)
      year <- year + 1
    }

    year <- seq(1, input$years)
    row1 <- c(0, amt, amt, amt)
    modalities <- rbind(year, no_contrib)
    modalities <- rbind(modalities, fixed_contrib)
    modalities <- rbind(modalities, growing_contrib)
    tab <- t(modalities)
    tab <- rbind(row1, tab)
    return(tab)
  })
  
   output$distPlot <- renderPlot({
     if (input$facet == "yes"){
       ggplot(data = dat(), aes(x = year, y = value, col=variable)) +
    geom_line() +
    ggtitle("Timelines") + 
      xlab("Year") +
      ylab("Amount") + 
      geom_area(aes(fill = variable)) +
    facet_wrap(. ~ variable)
     }   
     
     else{
       ggplot(data = dat(), aes(x = year, y = value, col=variable)) +
      geom_line() + 
      ggtitle("Timelines") + 
      xlab("Year") +
      ylab("Amount")
     }
   })

   output$table <- renderTable(
     tab(), title = "balances", bordered = TRUE
     )
   
     output$text <- renderText({
        paste("\n", "\n")
      })


}
shinyApp(ui = ui, server = server)


```
